### ISSUE TITLE
have a little problem with `inlay hints`

### ISSUE THREAD

**Issue by aklk1ng** [utilyre/sentiment.nvim#9]
Firstly, thank you for your work, it's a nice plugin for me.
I use this plugin for `inlay hint` in my nightly neovim, but your plugin will have a little problem that more positoins will be highlighted.
[lsp-inlayhints.nvim](https://github.com/lvimuser/lsp-inlayhints.nvim)

![2023-06-03_19-32](https://github.com/utilyre/sentiment.nvim/assets/94452368/e1c6c248-cb9c-479c-a15f-71ba18cefbcf)

**Comment by utilyre** [comment]
I think you should report this to upstream Neovim. Since it's highlighting multiple places although `nvim_buf_add_highlight` is called once for each pair character (twice in total).

You can refer to this part for more info: https://github.com/utilyre/sentiment.nvim/blob/ecde8d877881bb78fdb90060c0991e76770dbdbc/lua/sentiment/ui/Pair.lua#L38-L60

**Comment by aklk1ng** [comment]
@utilyre ,ok, thanks for answering.
